name: Sync OneNote to gh-pages

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3點 UTC
  workflow_dispatch: # 手動觸發

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (Latest)
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install latest onenote2md globally
        run: npm install -g onenote2md@1.2.5

      - name: install pubhtml
        run: npm install -g pubhtmlhere@2.2.2
        

      - name: Run onenote2md
        run: |
          onenote2md -u "https://diagmindtw.com/rawdocx/serve-docx.php?file=" \
                     -b "https://raw.githubusercontent.com/diagmind/onenote2md/refs/heads/main/kcms0.php" \
                     -M
                     -v

      - name: Add CNAME for GitHub Pages
        run: echo "vp.diagmindtw.com" > ./output/CNAME

      - name: Deploy ./output to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/vitepress_dist/vitepress_dist
          publish_branch: gh-pages
