name: Sync OneNote to gh-pages

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3點 UTC
  workflow_dispatch: # 手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (Latest)
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install latest onenote2md globally
        run: npm install -g onenote2md@1.2.10

      - name: install pubhtml
        run: npm install -g pubhtmlhere@2.2.8
        

      - name: Run onenote2md
        run: |
          onenote2md -u "https://diagmindtw.com/rawdocx/serve-docx.php?file=" \
                     -b "https://raw.githubusercontent.com/diagmind/onenote2md/refs/heads/main/kcms0.php" \
                     -M

      - name: Run onenote2md
        run: |
          cd output
          cd markdown
          npx vitepress build

      - name: Add CNAME for GitHub Pages
        run: echo "vp.diagmindtw.com" > ./output/markdown/.vitepress/dist/CNAME

     # # 3. 寫入 Pages metadata
     #  - name: Configure GitHub Pages
     #    uses: actions/configure-pages@v5   # 新版 v5

     #  # 4. 打包並上傳符合 Pages 規範的 artifact
     #  - name: Upload Pages artifact
     #    uses: actions/upload-pages-artifact@v3
     #    with:
     #      path: ./output/markdown/.vitepress/dist
  
      - name: Deploy ./output to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/markdown/.vitepress/dist
          publish_branch: gh-pages

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: github-pages
  #     url: ${{ steps.deployment.outputs.page_url }}
  #   permissions:
  #     pages: write
  #     id-token: write
  #   steps:
  #     - name: Deploy to GitHub Pages
  #       id: deployment
  #       uses: actions/deploy-pages@v4
