name: Sync OneNote to gh-pages

on:
  schedule:
    - cron: '0 3 * * *' # 每天凌晨3點 UTC
  workflow_dispatch: # 手動觸發

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js (Latest)
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - name: Install latest onenote2md and pubhtml
        run: |
          npm install -g onenote2md@1.3.51
          npm install -g pubhtmlhere@2.2.8

      - name: Run onenote2md
        run: |
          onenote2md -u "https://diagmindtw.com/rawdocx/serve-docx.php?file=" \
                     -b "https://diagmindtw.com/kcms0.php#edit" \
                     -M -v

      - name: Prepare VitePress Workspace
        run: |
          cd output
          mkdir vitepressworkspace
          cd vitepressworkspace
          npm init -y
          npm add -D vitepress
          npx vitepress init
          
          # 移除預設 example 並複製 markdown
          rm -rf docs
          cp -r ../markdown ./docs

          # 複製 config 設定
          mkdir -p docs/.vitepress
          cp ../markdown/.vitepress/config.mts docs/.vitepress/config.mts

      - name: Build VitePress site
        run: |
          cd output/vitepressworkspace
          npx vitepress build docs

      - name: Add CNAME for GitHub Pages
        run: echo "vp.diagmindtw.com" > ./output/vitepressworkspace/docs/.vitepress/dist/CNAME

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output/vitepressworkspace/docs/.vitepress/dist
          publish_branch: gh-pages
